
version: '3.8'
services:
  konomitv:
    image: konomitv
    container_name: KonomiTV
    build:
      context: .
    # OS 起動時にコンテナを自動起動
    restart: always
    # リッスンポートの設定
    ports:
      - '7000:7000'
    # 別の Docker コンテナで稼働中のサービスに host.docker.internal のホスト名でアクセスできるように
    # ref: https://qiita.com/skobaken/items/03a8b9d0e443745862ac
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # ボリュームのマウント設定
    # /host-rootfs はコンテナ内の KonomiTV からホストマシンのファイルを読み書きするために必要
    volumes:
      - type: bind
        source: './config.yaml'
        target: '/code/config.yaml'
      - type: bind
        source: './server/data/'
        target: '/code/server/data/'
      - type: bind
        source: './server/logs/'
        target: '/code/server/logs/'
      - type: bind
        source: '/'
        target: '/host-rootfs'
    # QSVEncC / VCEEncC を動作させる (Intel Graphics / AMD GPU にアクセスする) ために必要な設定
    # ホストマシン側のデバイスファイルをコンテナ側にマウントする
    devices:
      - '/dev/dri:/dev/dri'
